### ISSUE TITLE
Leaderboard Template

### ISSUE THREAD

**Issue by PeteGabriel** [Kroilon/kroilon#1]
Boas.

Abri este issue para explicar a situação actual do template "Leaderboard". Na última sessão do MegaShowBizz, foi pedido que a tab "Leaderboard" (ou antiga Dashboard) passasse a mostrar uma tabela de jogadores com diversas ligações, como por exemplo, para um gráfico de performance pessoal ou para um dashboard de estatísticas e dados pessoais.  Eu e o Nuno estivemos de volta desta tarefa e, após tentar utilizar um template para cada uma das ligações, optámos por usar apenas um template implementando uma lógica de show/hide com recurso a JQuery. 

Está em falta a ligação dos dados de cada jogador com cada uma das 3 partes do template. Ou seja, actualmente, quando se navega para um das ligações disponíveis (dashboard ou gráfico de performance) estamos a ver dados relativos ao utilizador "logged in", em vez de ser de um jogador em concreto.

**Comment by CaptainGabriel** [comment]
Boas !

Ontem introduzi no projecto a solução deste issue com recurso ao conceito de "Dynamic Templates". Basicamente, com uma determinada lógica, podemos permitir que um determinado template seja ou não mostrado. Esta solução permite que tenhamos templates separados e todos os "helpers" e lógica associada separada igualmente, permitindo uma manutenção de código mais fácil. 

Está em falta a ligação do jogador seleccionado através da tabela principal ao gráfico de performance e por isso não vou fechar ainda o issue. 

Se encontrarem bugs ou tiverem sugestões, por favor indiquem abaixo.

**Comment by Kroilon** [comment]
Espetacular. Bom trabalho Pedro! :-)

**Comment by CaptainGabriel** [comment]
Após o commit [ligação do gráfico de performance a um jogador especifico](https://github.com/Kroilon/kroilon/commit/df0650208ec94d211b8d5d6174526176e703cca7), gostaria de reportar os seguintes pontos:

*    Não estão a aparecer os "Badges". Não pecebo porquê uma vez que também não estou a ter nenhum erro na consola.
* O botão "Go Back" existe para que o utilizador possa voltar ao inicio (tabela), no entanto, quando mudamos de tab, este  não é o comportamento por defeito. Ao invés, é mantido o estado atual e o utilizador vai voltar, por exemplo, para o gráfico de performance se este foi o último  a ver visualizado. Penso que isto poderia ser melhorado.
* Aproveitamento de código pode ser MUITO melhorado nesta minha implementação, pelo que vou abrir um issue também para este facto.
* O gráfico de performance está agora ligado a  um utilizador especifico da tabela e não ao utilizador "logged in".

**Comment by PeteGabriel** [comment]
Entretanto, @Kroilon resolveu o problema dos badges não estarem a desaparecer. Bom trabalho ! 
Penso que este issue pode ser fechado.
